[2023-05-11T17:52:00.791+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-11T17:52:00.867+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark_process_data_14.spark_job_clean_data_by_ssh manual__2023-05-11T17:51:57.379697+00:00 [queued]>
[2023-05-11T17:52:00.916+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: spark_process_data_14.spark_job_clean_data_by_ssh manual__2023-05-11T17:51:57.379697+00:00 [queued]>
[2023-05-11T17:52:00.917+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T17:52:00.918+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-05-11T17:52:00.918+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-11T17:52:00.978+0000] {taskinstance.py:1383} INFO - Executing <Task(SSHOperator): spark_job_clean_data_by_ssh> on 2023-05-11 17:51:57.379697+00:00
[2023-05-11T17:52:00.991+0000] {standard_task_runner.py:54} INFO - Started process 648 to run task
[2023-05-11T17:52:01.001+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spark_process_data_14', 'spark_job_clean_data_by_ssh', 'manual__2023-05-11T17:51:57.379697+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/spark_process_scheduler.py', '--cfg-path', '/tmp/tmpkec3n1x4']
[2023-05-11T17:52:01.003+0000] {standard_task_runner.py:83} INFO - Job 187: Subtask spark_job_clean_data_by_ssh
[2023-05-11T17:52:01.005+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/spark_process_scheduler.py
[2023-05-11T17:52:01.352+0000] {task_command.py:384} INFO - Running <TaskInstance: spark_process_data_14.spark_job_clean_data_by_ssh manual__2023-05-11T17:51:57.379697+00:00 [running]> on host 09877495cfa0
[2023-05-11T17:52:01.365+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-11T17:52:01.729+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=pioneer22022001@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_process_data_14
AIRFLOW_CTX_TASK_ID=spark_job_clean_data_by_ssh
AIRFLOW_CTX_EXECUTION_DATE=2023-05-11T17:51:57.379697+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-11T17:51:57.379697+00:00
[2023-05-11T17:52:01.731+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-05-11T17:52:01.917+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-05-11T17:52:01.977+0000] {base.py:71} INFO - Using connection ID 'ssh_connection_spark' for task execution.
[2023-05-11T17:52:01.980+0000] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-05-11T17:52:05.033+0000] {ssh.py:341} INFO - Failed to connect. Sleeping before retry attempt 1
[2023-05-11T17:52:06.114+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-11T17:52:12.809+0000] {ssh.py:341} INFO - Failed to connect. Sleeping before retry attempt 2
[2023-05-11T17:52:16.428+0000] {local_task_job.py:228} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-05-11T17:52:16.434+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 648. PIDs of all processes in the group: [648]
[2023-05-11T17:52:16.435+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 648
[2023-05-11T17:52:16.436+0000] {taskinstance.py:1562} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-05-11T17:52:16.548+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=648, status='terminated', exitcode=0, started='17:52:00') (648) terminated with exit code 0
