[2023-05-15T08:22:53.639+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-15T08:22:53.684+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: job_1_tranvietcuong.end_task scheduled__2023-05-11T21:25:00+00:00 [queued]>
[2023-05-15T08:22:53.721+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: job_1_tranvietcuong.end_task scheduled__2023-05-11T21:25:00+00:00 [queued]>
[2023-05-15T08:22:53.722+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-15T08:22:53.722+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-05-15T08:22:53.723+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-15T08:22:53.774+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): end_task> on 2023-05-11 21:25:00+00:00
[2023-05-15T08:22:53.790+0000] {standard_task_runner.py:54} INFO - Started process 192 to run task
[2023-05-15T08:22:53.805+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'job_1_tranvietcuong', 'end_task', 'scheduled__2023-05-11T21:25:00+00:00', '--job-id', '461', '--raw', '--subdir', 'DAGS_FOLDER/tranvietcuong.py', '--cfg-path', '/tmp/tmps3m34tvr']
[2023-05-15T08:22:53.808+0000] {standard_task_runner.py:83} INFO - Job 461: Subtask end_task
[2023-05-15T08:22:53.812+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/tranvietcuong.py
[2023-05-15T08:22:54.231+0000] {task_command.py:384} INFO - Running <TaskInstance: job_1_tranvietcuong.end_task scheduled__2023-05-11T21:25:00+00:00 [running]> on host 1158220c4572
[2023-05-15T08:22:54.242+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-15T08:22:54.533+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=job_1_tranvietcuong
AIRFLOW_CTX_TASK_ID=end_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-11T21:25:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-11T21:25:00+00:00
[2023-05-15T08:22:54.535+0000] {logging_mixin.py:117} INFO - timeout
[2023-05-15T08:22:54.552+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2023-05-15T08:22:54.569+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tranvietcuong.py", line 64, in timeout_callback
    raise AirflowException('Sensor timed out')
airflow.exceptions.AirflowException: Sensor timed out
[2023-05-15T08:22:54.576+0000] {warnings.py:110} WARNING - /usr/local/lib/python3.7/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2023-05-15T08:22:54.594+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=job_1_tranvietcuong, task_id=end_task, execution_date=20230511T212500, start_date=20230515T082253, end_date=20230515T082254
[2023-05-15T08:22:54.639+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 461 for task end_task (Sensor timed out; 192)
[2023-05-15T08:22:54.686+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-05-15T08:22:54.791+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
