[2023-05-19T04:05:51.628+0000] {processor.py:156} INFO - Started process (PID=41) to work on /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:05:51.640+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/azure_cosmos_with_provider.py for tasks to queue
[2023-05-19T04:05:51.663+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:05:51.662+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:05:52.134+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:05:52.133+0000] {base.py:71} INFO - Using connection ID 'azure_cosmos_default' for task execution.
[2023-05-19T04:05:52.153+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:05:52.152+0000] {_universal.py:513} INFO - Request URL: 'https://tranvietcuonghust.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.3.1 Python/3.7.16 (Linux-5.19.0-41-generic-x86_64-with-debian-10.13)'
No body was attached to the request
[2023-05-19T04:05:52.551+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:05:52.550+0000] {_universal.py:549} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Fri, 19 May 2023 04:05:52 GMT'
[2023-05-19T04:05:52.565+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:05:52.559+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/azure_cosmos_with_provider.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/azure_cosmos_with_provider.py", line 29, in <module>
    container_proxy = client.get_container_client(container_link)
AttributeError: 'CosmosClient' object has no attribute 'get_container_client'
[2023-05-19T04:05:52.567+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:05:52.695+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/azure_cosmos_with_provider.py took 1.089 seconds
[2023-05-19T04:06:23.503+0000] {processor.py:156} INFO - Started process (PID=56) to work on /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:06:23.513+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/azure_cosmos_with_provider.py for tasks to queue
[2023-05-19T04:06:23.515+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:06:23.514+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:06:23.798+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:06:23.798+0000] {base.py:71} INFO - Using connection ID 'azure_cosmos_default' for task execution.
[2023-05-19T04:06:23.817+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:06:23.816+0000] {_universal.py:513} INFO - Request URL: 'https://tranvietcuonghust.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.3.1 Python/3.7.16 (Linux-5.19.0-41-generic-x86_64-with-debian-10.13)'
No body was attached to the request
[2023-05-19T04:06:24.154+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:06:24.154+0000] {_universal.py:549} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Fri, 19 May 2023 04:06:23 GMT'
[2023-05-19T04:06:24.163+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:06:24.159+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/azure_cosmos_with_provider.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/azure_cosmos_with_provider.py", line 29, in <module>
    container_proxy = client.get_container_client(container_link)
AttributeError: 'CosmosClient' object has no attribute 'get_container_client'
[2023-05-19T04:06:24.165+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:06:24.246+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/azure_cosmos_with_provider.py took 0.751 seconds
[2023-05-19T04:06:54.487+0000] {processor.py:156} INFO - Started process (PID=81) to work on /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:06:54.502+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/azure_cosmos_with_provider.py for tasks to queue
[2023-05-19T04:06:54.505+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:06:54.504+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:06:54.915+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:06:54.914+0000] {base.py:71} INFO - Using connection ID 'azure_cosmos_default' for task execution.
[2023-05-19T04:06:54.932+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:06:54.932+0000] {_universal.py:513} INFO - Request URL: 'https://tranvietcuonghust.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.3.1 Python/3.7.16 (Linux-5.19.0-41-generic-x86_64-with-debian-10.13)'
No body was attached to the request
[2023-05-19T04:06:55.282+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:06:55.280+0000] {_universal.py:549} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Fri, 19 May 2023 04:06:54 GMT'
[2023-05-19T04:06:55.287+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:06:55.283+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/azure_cosmos_with_provider.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/azure_cosmos_with_provider.py", line 29, in <module>
    container_proxy = client.get_container_client(container_link)
AttributeError: 'CosmosClient' object has no attribute 'get_container_client'
[2023-05-19T04:06:55.288+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:06:55.343+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/azure_cosmos_with_provider.py took 0.879 seconds
[2023-05-19T04:07:26.235+0000] {processor.py:156} INFO - Started process (PID=107) to work on /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:07:26.246+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/azure_cosmos_with_provider.py for tasks to queue
[2023-05-19T04:07:26.252+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:07:26.251+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:07:26.557+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:07:26.557+0000] {base.py:71} INFO - Using connection ID 'azure_cosmos_default' for task execution.
[2023-05-19T04:07:26.570+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:07:26.570+0000] {_universal.py:513} INFO - Request URL: 'https://tranvietcuonghust.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.3.1 Python/3.7.16 (Linux-5.19.0-41-generic-x86_64-with-debian-10.13)'
No body was attached to the request
[2023-05-19T04:07:26.909+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:07:26.908+0000] {_universal.py:549} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Fri, 19 May 2023 04:07:26 GMT'
[2023-05-19T04:07:26.913+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:07:26.910+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/azure_cosmos_with_provider.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/azure_cosmos_with_provider.py", line 29, in <module>
    container_proxy = client.get_container_client(container_link)
AttributeError: 'CosmosClient' object has no attribute 'get_container_client'
[2023-05-19T04:07:26.914+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:07:26.964+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/azure_cosmos_with_provider.py took 0.741 seconds
[2023-05-19T04:07:57.209+0000] {processor.py:156} INFO - Started process (PID=141) to work on /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:07:57.220+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/azure_cosmos_with_provider.py for tasks to queue
[2023-05-19T04:07:57.223+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:07:57.223+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:07:57.501+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:07:57.500+0000] {base.py:71} INFO - Using connection ID 'azure_cosmos_default' for task execution.
[2023-05-19T04:07:57.526+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:07:57.525+0000] {_universal.py:513} INFO - Request URL: 'https://tranvietcuonghust.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.3.1 Python/3.7.16 (Linux-5.19.0-41-generic-x86_64-with-debian-10.13)'
No body was attached to the request
[2023-05-19T04:07:57.846+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:07:57.846+0000] {_universal.py:549} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Fri, 19 May 2023 04:07:56 GMT'
[2023-05-19T04:07:57.849+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:07:57.847+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/azure_cosmos_with_provider.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/azure_cosmos_with_provider.py", line 29, in <module>
    container_proxy = client.get_container_client(container_link)
AttributeError: 'CosmosClient' object has no attribute 'get_container_client'
[2023-05-19T04:07:57.850+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:07:57.896+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/azure_cosmos_with_provider.py took 0.698 seconds
[2023-05-19T04:08:28.886+0000] {processor.py:156} INFO - Started process (PID=167) to work on /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:08:28.895+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/azure_cosmos_with_provider.py for tasks to queue
[2023-05-19T04:08:28.897+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:08:28.897+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:08:29.069+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:08:29.069+0000] {base.py:71} INFO - Using connection ID 'azure_cosmos_default' for task execution.
[2023-05-19T04:08:29.084+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:08:29.083+0000] {_universal.py:513} INFO - Request URL: 'https://tranvietcuonghust.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.3.1 Python/3.7.16 (Linux-5.19.0-41-generic-x86_64-with-debian-10.13)'
No body was attached to the request
[2023-05-19T04:08:29.418+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:08:29.417+0000] {_universal.py:549} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Fri, 19 May 2023 04:08:28 GMT'
[2023-05-19T04:08:29.421+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:08:29.419+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/azure_cosmos_with_provider.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/azure_cosmos_with_provider.py", line 29, in <module>
    container_proxy = client.get_container_client(container_link)
AttributeError: 'CosmosClient' object has no attribute 'get_container_client'
[2023-05-19T04:08:29.422+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:08:29.463+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/azure_cosmos_with_provider.py took 0.586 seconds
[2023-05-19T04:08:59.774+0000] {processor.py:156} INFO - Started process (PID=192) to work on /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:08:59.785+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/azure_cosmos_with_provider.py for tasks to queue
[2023-05-19T04:08:59.788+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:08:59.788+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:09:00.054+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:09:00.053+0000] {base.py:71} INFO - Using connection ID 'azure_cosmos_default' for task execution.
[2023-05-19T04:09:00.072+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:09:00.072+0000] {_universal.py:513} INFO - Request URL: 'https://tranvietcuonghust.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.3.1 Python/3.7.16 (Linux-5.19.0-41-generic-x86_64-with-debian-10.13)'
No body was attached to the request
[2023-05-19T04:09:00.388+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:09:00.387+0000] {_universal.py:549} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Fri, 19 May 2023 04:08:59 GMT'
[2023-05-19T04:09:00.393+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:09:00.390+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/azure_cosmos_with_provider.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/azure_cosmos_with_provider.py", line 29, in <module>
    container_proxy = client.get_container_client(container_link)
AttributeError: 'CosmosClient' object has no attribute 'get_container_client'
[2023-05-19T04:09:00.395+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:09:00.451+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/azure_cosmos_with_provider.py took 0.693 seconds
[2023-05-19T04:12:20.722+0000] {processor.py:156} INFO - Started process (PID=42) to work on /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:12:20.726+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/azure_cosmos_with_provider.py for tasks to queue
[2023-05-19T04:12:20.729+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:12:20.728+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:12:21.206+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:12:21.206+0000] {base.py:71} INFO - Using connection ID 'azure_cosmos_default' for task execution.
[2023-05-19T04:12:21.226+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:12:21.225+0000] {_universal.py:513} INFO - Request URL: 'https://tranvietcuonghust.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.3.1 Python/3.7.16 (Linux-5.19.0-41-generic-x86_64-with-debian-10.13)'
No body was attached to the request
[2023-05-19T04:12:21.613+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:12:21.612+0000] {_universal.py:549} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Fri, 19 May 2023 04:12:21 GMT'
[2023-05-19T04:12:21.618+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:12:21.615+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/azure_cosmos_with_provider.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/azure_cosmos_with_provider.py", line 29, in <module>
    container_proxy = client.get_container_client(container_link)
AttributeError: 'CosmosClient' object has no attribute 'get_container_client'
[2023-05-19T04:12:21.620+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:12:21.672+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/azure_cosmos_with_provider.py took 0.978 seconds
[2023-05-19T04:18:17.636+0000] {processor.py:156} INFO - Started process (PID=43) to work on /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:18:17.645+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/azure_cosmos_with_provider.py for tasks to queue
[2023-05-19T04:18:17.649+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:18:17.648+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:18:18.216+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:18:18.215+0000] {base.py:71} INFO - Using connection ID 'azure_cosmos_default' for task execution.
[2023-05-19T04:18:18.235+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:18:18.234+0000] {_universal.py:513} INFO - Request URL: 'https://tranvietcuonghust.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.3.1 Python/3.7.16 (Linux-5.19.0-41-generic-x86_64-with-debian-10.13)'
No body was attached to the request
[2023-05-19T04:18:18.877+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:18:18.877+0000] {_universal.py:549} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Fri, 19 May 2023 04:18:18 GMT'
[2023-05-19T04:18:18.907+0000] {logging_mixin.py:117} INFO - [2023-05-19T04:18:18.903+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/azure_cosmos_with_provider.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/azure_cosmos_with_provider.py", line 29, in <module>
    container_proxy = client.get_container_client(container_link)
AttributeError: 'CosmosClient' object has no attribute 'get_container_client'
[2023-05-19T04:18:18.908+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T04:18:19.038+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/azure_cosmos_with_provider.py took 1.415 seconds
[2023-05-19T09:07:14.764+0000] {processor.py:156} INFO - Started process (PID=30) to work on /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T09:07:14.780+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/azure_cosmos_with_provider.py for tasks to queue
[2023-05-19T09:07:14.784+0000] {logging_mixin.py:117} INFO - [2023-05-19T09:07:14.783+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T09:07:15.468+0000] {logging_mixin.py:117} INFO - [2023-05-19T09:07:15.467+0000] {base.py:71} INFO - Using connection ID 'azure_cosmos_default' for task execution.
[2023-05-19T09:07:15.551+0000] {logging_mixin.py:117} INFO - [2023-05-19T09:07:15.550+0000] {_universal.py:513} INFO - Request URL: 'https://tranvietcuonghust.documents.azure.com:443/'
Request method: 'GET'
Request headers:
    'Cache-Control': 'no-cache'
    'x-ms-version': 'REDACTED'
    'x-ms-documentdb-query-iscontinuationexpected': 'REDACTED'
    'x-ms-date': 'REDACTED'
    'authorization': 'REDACTED'
    'Accept': 'application/json'
    'Content-Length': '0'
    'User-Agent': 'azsdk-python-cosmos/4.3.1 Python/3.7.16 (Linux-5.19.0-41-generic-x86_64-with-debian-10.13)'
No body was attached to the request
[2023-05-19T09:07:16.157+0000] {logging_mixin.py:117} INFO - [2023-05-19T09:07:16.156+0000] {_universal.py:549} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json'
    'Content-Location': 'REDACTED'
    'Server': 'Microsoft-HTTPAPI/2.0'
    'x-ms-max-media-storage-usage-mb': 'REDACTED'
    'x-ms-media-storage-usage-mb': 'REDACTED'
    'x-ms-databaseaccount-consumed-mb': 'REDACTED'
    'x-ms-databaseaccount-reserved-mb': 'REDACTED'
    'x-ms-databaseaccount-provisioned-mb': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'x-ms-gatewayversion': 'REDACTED'
    'Date': 'Fri, 19 May 2023 09:07:15 GMT'
[2023-05-19T09:07:16.162+0000] {logging_mixin.py:117} INFO - [2023-05-19T09:07:16.158+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/azure_cosmos_with_provider.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/azure_cosmos_with_provider.py", line 29, in <module>
    container_proxy = client.get_container_client(container_link)
AttributeError: 'CosmosClient' object has no attribute 'get_container_client'
[2023-05-19T09:07:16.164+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/azure_cosmos_with_provider.py
[2023-05-19T09:07:16.231+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/azure_cosmos_with_provider.py took 1.502 seconds
